[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["ls -la /app/ && ls -la /app/public/ 2>/dev/null || echo 'NO PUBLIC DIR'"]

[start]
cmd = "node src/index.js"
